### ISSUE TITLE
create generalized shear generator classes

### ISSUE THREAD

**Issue by beckermr** [beckermr/egret#13]

**Comment by esheldon** [comment]
Example ways to specify in the config file
```
shear:
    type: "const"
    shears: [0.08, 0.00]

shear:
    # draw randomly
    type: "const"
    shears: [
            [ 0.08, 0.00],
            [-0.08, 0.00],
            [ 0.04, 0.00],
            [-0.04, 0.00],
            [ 0.00, 0.08],
            [ 0.00,-0.08],
            [ 0.00, 0.04],
            [ 0.00,-0.04]
          ]


# specify a model, which should match up to something
# egret understands
shear:
    type: "varying"
    model: "blah"
    pars: [...]
```

**Comment by esheldon** [comment]
Eric is interested in some fields that are more like great3, and would require this improvement.

I can implement this.  Can you please point me where in the code I should like?

**Comment by beckermr** [comment]
This is a big feature to implement. You will need to create a shear generator base class and the modify the code in various other places to accept this class and use it compute shears. The same thing needs to be done with the observing conditions. Some thought on how to make the best internal APIs for these these is definitely required.

**Comment by esheldon** [comment]
I just pushed some changes that implement this.  Here is an example config that works

https://github.com/esheldon/egretsims/blob/master/config/v10test.yaml

This reminds me, we still need to simplify the path, output_base stuff

**Comment by esheldon** [comment]
(referring to my fork https://github.com/esheldon/egret/commits/master)
