### ISSUE TITLE
add stars to sims

### ISSUE THREAD

**Issue by esheldon** [beckermr/egret#19]
In the config file

```
stars:
    frac_stars: 0.05
    # other parameters?
```

Then just render a psf in the stamp.

**Comment by beckermr** [comment]
A little more context here might help.

**Comment by esheldon** [comment]
The idea is to see if metacal can work with stellar contamination.  These should get zero response, but that's ok since the estimator (approximately)
```
sum(e)/sum(R)
```

**Comment by beckermr** [comment]
Ahhh ok. I guess the rendered psf and the recorded PSF for the stamp should be the same intrinsic profile, but have different noise realizations? This would be equivalent to assuming that on average the PSF reconstruction is perfect, but that you get a different noise realization from the reconstruction.

**Comment by esheldon** [comment]
Yeah, the `star` would have the same noise that is added to the galaxies.
